name: Run Jupyter Notebook Manually

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
permissions:
  id-token: write
  pages: write

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        pip install jupyter nbconvert pandas numpy matplotlib seaborn scikit-learn

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute heart_disease_predictor/heart_disease_prediction.ipynb --output heart_disease_prediction.ipynb

    - name: Upload Executed Notebook
      uses: actions/upload-artifact@v3
      with:
        name: heart_disease_prediction.ipynb
        path: heart_disease_predictor/heart_disease_prediction.ipynb


